services:
  backend:



    build: ./backend
    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ragdb
      SPRING_DATASOURCE_USERNAME: postgres




      SPRING_DATASOURCE_PASSWORD: postgres
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      VOYAGE_API_KEY: ${VOYAGE_API_KEY}

    ports:
      - "8080:8080"



  frontend:
    build: ./frontend




    depends_on:
      - backend

    ports:
      - "888:80"



  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped



    ports:
      - "5432:5432"
    environment:



      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb

    volumes:
      - postgres_data:/var/lib/postgresql/data






volumes:
  postgres_data: