spring.application.name=rag-assistant

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG


#logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

app.cors.allowed-origins=http://localhost:888

anthropic.api-key=${ANTHROPIC_API_KEY}
anthropic.chat-model=claude-sonnet-4-6
anthropic.embedding-model=voyage-3
anthropic.max-tokens=1028

rag.chunk-size=500
rag.chunk-overlap=50
rag.top-k=5


voyage.api-key=${VOYAGE_API_KEY}
management.endpoints.web.exposure.include=health
management.enpoint.health.show-details=never